### ISSUE TITLE
Segfault in alignment

### ISSUE THREAD

**Issue by gui11aume** [gui11aume/smmfdp#1]
The following read triggers a segmentation fault (apparently at alignment time).

`TCTCATTCTGTCTTATTTTACCGCAACCCCAAATCGACAATGCACGACAAAGGAAGCAGAACAGATATTTAGATTGCCTCTCGTTTTCTCTCCCATATTA`

**Comment by ezorita** [comment]
What genome? I cannot reproduce it.

**Comment by gui11aume** [comment]
Drosophila melanogaster dmel-all-chromosome-r6.27.fasta
