### ISSUE TITLE
Pine bwt search FAIL

### ISSUE THREAD

**Issue by ezorita** [gui11aume/smmfdp#3]
Reference:
willow:/home/rcortini/work/CRG/projects/sesame-manuscript/benchmark/data/membenchmark/smmfdp/GCA(...).fna

Input:
willow:/home/rcortini/work/CRG/projects/sesame-manuscript/benchmark/data/membenchmark/mini.fasta

**Comment by ezorita** [comment]
Apparently mem loop have non-consistent position indices.

**Comment by gui11aume** [comment]
The issue is some overflow in the data structures of the index. We need to replace this part of the code to accommodate larger genomes. We will proceed to replacing it by some code written by @ezorita for another project.
