### ISSUE TITLE
Reported infinite mapping quality

### ISSUE THREAD

**Issue by rcortini** [gui11aume/smmfdp#6]
On Drosophila genome smmfdp reports infinite mapping quality (0 in last column of output) for the following sequence:

```
> X;23352772;23352822
GCTGTGAGTTTTTCACACGTGCTAAACGGCCTGCCTGAACTCTGTGATGC
```

smmfdp reports mapping at chromosome Y:914439:-

**Comment by gui11aume** [comment]
On commit b9a5ba6236 the reported quality is 1.0. I am not sure what caused this, but it seems that it was fixed among other things in the last commits.
